### ISSUE TITLE
How do we install without network access?

### ISSUE THREAD

**Issue by stephane-tremblay5** [mbl-35/wsl-vpnkit#2]
Hello,
I thought the point of this was to allow network/internet access via a WSL2 Ubuntu environment that doesn't have it already. But the readme assumes that we have network/internet connectivity...

Can you please provide step-by-step instructions on how to install this via PowerShell instead? Or maybe provide a ps1 script that would automate the process like you did with your bash script?

Thank you

**Comment by mbl-35** [comment]
Hello, 
You are right, internet access is required during installation.
The procedure is to deactivate the VPN (internet access then provided by the FIA) and install the kit. Then you can activate the VPN.

However, I will put this repo in deprecated state, since with the creation of a wsl2 instance of the original [sakai135/wsl-vpnkit](https://github.com/sakai135/wsl-vpnkit) repo, the procedure is simpler and more robust...

You can :
- manual install it by (needs network acces from windows):
  - download the latest `wsl-vpnkit.tar.gz` release at https://github.com/sakai135/wsl-vpnkit/releases,
  - import this wsl2 instance with command: `wsl --import wsl-vpnkit <windows-wsl-storage> c:\Users\<yourname>\Downloads\wsl-vpnkit.tar.gz`
  - starts the kit `wsl -d wsl-vpnkit service wsl-vpnkit-start`
- use my wsl-vpnkit-tray to start/stop (autostart) the wsl2 wsl-vpnkit instance ..
- when started, you will hase net access onto your others wsl2 instances

If you use scoop, I am writting a specific buckets to automate the install process (no adm rigths, but need wsl2 capabilities), both for wsl-vpnkit and wsl-vpnkit-tray

Hope this help :)

**Comment by stephane-tremblay5** [comment]
Ah yes. Thank you very much for the update. :)
The other wsl-vpnkit works like a charm.
